# Generated by Django 3.2.7 on 2021-10-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211001_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
