# Generated by Django 3.2.7 on 2021-10-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='scope_avrage',
        ),
    ]
