# Generated by Django 3.2.7 on 2021-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211001_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_rates',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
